---

name: Deliver Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'xslt/**'
      - 'entrypoint.py'

jobs:
  deliver-image:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: dockerhub-auth
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: build-and-push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile
          tags: 'delnaught/xmltv-programmes:latest'

    
